version: '3'

services:

  hello:
    environment:
      - NODE_ENV=development
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hello
    volumes:
      - ./:/home/node/app
      - hellofiles:/home/node/app/.config
      - hellofiles:/home/node/app/.npm
      - hellofiles:/home/node/app/node_modules
    ports:
      - "8103:8103"
      - "9229:9229"
    command: /bin/sh -c 'npm install && npm run debug'

volumes:
  hellofiles:
